//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dueño
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dueño()
        {
            this.Animales = new HashSet<Animales>();
            this.Historial_Medico = new HashSet<Historial_Medico>();
        }
    
        public string ID_Dueño_Cedula { get; set; }
        public string Nombre_Dueño { get; set; }
        public string Apellido_Dueño { get; set; }
        public string Dirección_Dueño { get; set; }
        public string Telefono_Dueño { get; set; }
        public string Email_Dueño { get; set; }
        public Nullable<int> Est_Dueño { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animales> Animales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Medico> Historial_Medico { get; set; }
    }
}
