//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialista()
        {
            this.Especialista_Horario = new HashSet<Especialista_Horario>();
        }
    
        public string ID_Especialista_Cedula { get; set; }
        public string Nombre_Espe { get; set; }
        public string Apellido_Espe { get; set; }
        public string Telefono_Espe { get; set; }
        public string Email_Espe { get; set; }
        public string Especialización_Espe { get; set; }
        public Nullable<int> Est_Espe { get; set; }
        public Nullable<int> ID_Servicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especialista_Horario> Especialista_Horario { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
