//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioModelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista_Horario
    {
        public int ID_Esp_Hora { get; set; }
        public string ID_Especialista_Cedula { get; set; }
        public Nullable<int> ID_Horario { get; set; }
    
        public virtual Especialista Especialista { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
